---
title: "osduhs"
author: "Ben Brew"
date: "December 21, 2017"
output: html_document
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE}

library(tidyverse)
library(glmnet)
library(broom)
library(glmnet)
library(doParallel) 
library(preprocessCore)

registerDoParallel(2)

# source('global.R')
source('functions.R')

# load global to get survey data
load('data/processed_survey_data.RData')

# extract the "2015_ontario_student_drug_use_and_health_survey" (10th element in list)
dat <- survey[[10]]

# convert date to date object 
dat$demo_osduhs_date <- get_date_osduhs(dat$demo_osduhs_date)

# for the time being flag and remove any column with over 1000 NA entries (talk to joe about this)
dat <- dat[, apply(dat, 2, function(x) length(which(is.na(x))) < 1000)]

# recode dat$demo_osduhs_sex_male
colnames(dat) <- ifelse(grepl('demo_osduhs_sex_male', colnames(dat), fixed = TRUE), 'demo_osduhs_sex', colnames(dat))

# recode body weight variable 
get_body_weight_osduhs <- function(dat = dat){
  temp <- unlist(lapply(strsplit(as.character(dat$hw_osduhs_weight), 
                          '/', 
                          fixed = TRUE), function(x){
                            x[1]
                          }))
  unique_pounds <- as.character(unique(sort(temp)))
  
  temp <- as.data.frame(cbind(pounds = unique_pounds, 
                                sequence = seq(1, length(unique_pounds), 1)))
  temp$sequence <- as.numeric(temp$sequence)
  
  # split into 5 categories using sequence 
  temp$new_weight <- ifelse(temp$sequence > 0 & temp$sequence <=6, '80_105',
                            ifelse(temp$sequence > 7 & temp$sequence <=12, '106_135', 
                                   ifelse(temp$sequence > 13 & temp$sequence <= 18, '136_165',
                                          ifelse(temp$sequence > 19 & temp$sequence <=24, '166_195',
                                                 ifelse(temp$sequence > 25 & temp$sequence <= 30, '196_225',
                                                        ifelse(temp$sequence > 31 & temp$sequence <=36, '226_255', '255_up'))))))
  
  temp$sequence <- NULL
  
  dat1 <- left_join(dat, temp, by = c('hw_osduhs_weigth' = 'pounds'))
  
  # l
                                                               
}
sort(unique(dat$hw_osduhs_weight))
sort(unique(temp))

# remove variable that won't be in model (we have extra sex variable so remove that too)
dat$demo_osduhs_sex_female <- dat$demo_osduhs_ids <- dat$hw_osduhs_class_ids <- 
  dat$demo_osduhs_time_started_survey <- dat$demo_osduhs_time_ended_survey <- NULL 

```

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE}
# function that takes an outcome (any variable by demo) and regresses on all demo variables
# default estimates a lasso
get_glm <- function(model_data = dat, 
                    model_type, 
                    weights = NULL) {

  # get list to store dta
  result_list <- list()
  
  # remove NAS
  model_data <- as.data.frame(model_data[complete.cases(model_data),])
  
  # get weight vector
  weight_index <- grepl('demo_osduhs_pop_weight', colnames(model_data))
  weight_vector <-model_data[, weight_index]
  
  if(!is.null(weights)) {
    weights <- weight_vector
  }
  # remove weight from data 
  model_data <- model_data[, !grepl('demo_osduhs_pop_weight', colnames(model_data))]
  
  # for the time being remove any factors that have more than 10 levels (ill clean them later, just rushed to      get this to xing)
  model_data <- model_data[, apply(model_data, 2, function(x) length(unique(x)) < 10)]
  
  # get outcome and feature data (for time being anything that is demo is feature)
  outcome_data <- model_data[, !grepl('^demo', colnames(model_data))]
  demo_data <- model_data[, grepl('^demo', colnames(model_data))]
  
  # only keep outcome variable that have two levels
  outcome_data <- outcome_data[, apply(outcome_data, 2, function(x) length(unique(x)) < 3)]

  # loop through outcome_dat and bind each outcome variable with feature dat
  for(i in 1:ncol(outcome_data)){

    # get outcome variable and the name (to store later)
    y_outcome <- outcome_data[,i]
    y_outcome_name <- names(outcome_data)[i]
    
    # get target class (always second in alphabetical order so you can store this as well)
    target_class <- sort(unique(y_outcome))[2]

    # set the alpha parameter based on model type
    if(model_type == 'lasso') {
      alpha_val <- 1
    } 
    if(model_type =='ridge'){
      alpha_val <- 0
    }
    
    # do ridge or lasso
    if(grepl('lasso|ridge', model_type)){
      
      if(!is.null(weights)) {
        weights <- weight_vector
      } else {
        weights <- rep.int(1, nrow(demo_data))
      }
    
    # runs model with 5 fold cv and we keep the lambda with minimum cv error
    cv_model = cv.glmnet(model.matrix(~.,demo_data), 
                         nfolds = 5,
                         y_outcome,
                         alpha = alpha_val, 
                         family = 'binomial',
                         weights = weights,
                         parallel = TRUE)

    lambda_index = which(cv_model$lambda == cv_model$lambda.min) 

    # creat result table with odds ratios tha correspond to the best lamnd (minimum)
    model_result <- data.frame(outcome_name = y_outcome_name, target_class = target_class, coef.name = dimnames(coef(cv_model))[[1]], coef.value = matrix(exp(coef(cv_model, s = "lambda.min"))))
  
    } else {
      
      # do normal logit with no regularization
      temp_mod_data <- as.data.frame(cbind(y_outcome = y_outcome, demo_data))
      
      # loop though colnames (without demo) and estimate logit
      model_result <- glm(y_outcome~. , family = 'binomial', weights = weights, data = temp_mod_data)
      model_result <- cbind(tidy(model_result), odds_ratio = exp(model_result$coefficients), target_class = target_class)
      model_result$odds_ratio.names <- NULL
      model_result$outcome_var <- y_outcome_name
      model_result$sig <- ifelse(model_result$p.value < 0.05, 'significant', 'not_statistically_significant')
    
    }
    
   result_list[[i]] <- model_result
   print(i)
  }
  
  logit_results <- do.call(rbind, result_list)

  return(logit_results)
}

lasso_results <- get_glm(model_data = dat, model_type = 'lasso', weights = NULL)
write_csv(lasso_results, '~/Desktop/lasso_results.csv')
ridge_results <- get_glm(model_data = dat, model_type = 'ridge', weights = NULL)
write_csv(ridge_results, '~/Desktop/ridge_results.csv')
logit_results <- get_glm(model_data = dat, model_type = 'no_reularization', weights = NULL)
write_csv(logit_results, '~/Desktop/logit_results.csv')


```


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE}
# analysis of 4 outcome sof interest 
# cigs, binge, cannabis, opiods. 
# by race, parents, residence, questionaire, sex, language

```
