---
title: "Model examples"
author: "Ben Brew"
date: "January 14, 2018"
output: html_document
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE}
###{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = FALSE}


# If get_new_data is set to True,
# make sure that you are working within the "insider" virtualenv

# Libraries
library(tidyverse)
library(glmnet)
library(knitr)
library(Hmisc)
library(RColorBrewer)
library(plotly)
library(databrew)
library(ggmap)
library(reshape2)
library(memisc)
library(texreg)


# Turn off scientific notation
options(scipen = '999')

# Basic knitr options
knitr::opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, # Render report, even with errors
               cache = F)

# source functions
source('functions.R')

# Get all locationsd
if('preprocess_survey_data.RData' %in% dir('data')){
  load('data/preprocess_survey_data.RData')
} else { 
  source('global.R')
}


# get folder names
path_to_data <-  'data/survey_data'
survey_folders <- list.files(path_to_data)
survey_folders
osduhs <- survey[[10]]

```

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}

# recode presciption pain pill columns to be binary 
str(osduhs)
summary(as.factor(osduhs$hw_osduhs_12_months_pain_pill_without_prescription))
osduhs$pain_pill_no_pres <- ifelse(grepl("don't know|never used", osduhs$hw_osduhs_12_months_pain_pill_without_prescription), 'No', 
                                   ifelse(is.na(osduhs$hw_osduhs_12_months_pain_pill_without_prescription), 
                                          NA, 'Yes'))


# get mother and father columns by aggregating the 3 columns associated with both 
summary(as.factor(osduhs$demo_osduhs_mother_home))
summary(as.factor(osduhs$demo_osduhs_step_mother_home))
summary(as.factor(osduhs$demo_osduhs_adop_mother_home))

# father 
osduhs <- osduhs %>%
  mutate(demo_osduhs_father_type_at_home = ifelse(demo_osduhs_father_home == 'yes',
                                      'Biological father',
                                      ifelse(demo_osduhs_adop_father_home == 'yes',
                                             'Adopted father',
                                             ifelse(demo_osduhs_step_father_home == 'yes',
                                                    'Step father', 'No father figure at home'))))

osduhs <- osduhs[,!grepl('father_home', names(osduhs))]


# mother 
osduhs <- osduhs %>%
  mutate(demo_osduhs_mother_type_at_home = ifelse(demo_osduhs_mother_home == 'yes',
                                      'Biological mother',
                                      ifelse(demo_osduhs_adop_mother_home == 'yes',
                                             'Adopted mother',
                                             ifelse(demo_osduhs_step_mother_home == 'yes',
                                                    'Step mother', 'No mother figure at home'))))

osduhs <- osduhs[,!grepl('mother_home', names(osduhs))]

# recode demo_osduhs_father_edu
summary(as.factor(osduhs$demo_osduhs_father_edu))
osduhs$demo_osduhs_father_edu <- ifelse(grepl('attended', osduhs$demo_osduhs_father_edu), 
                                        'Attended college or hs or uni',
                                        ifelse(grepl('graduated', osduhs$demo_osduhs_father_edu),
                                               'graduated college or hs or uni',
                                               ifelse(grepl("don't", osduhs$demo_osduhs_father_edu),
                                                      'Dont know',
                                                      ifelse(is.na(osduhs$demo_osduhs_father_edu),
                                                             NA, 
                                                             ifelse(grepl('did not', osduhs$demo_osduhs_father_edu),
                                                                          'No highschool', 'No father')))))

# recode demo_osduhs_mother_edu
summary(as.factor(osduhs$demo_osduhs_mother_edu))
osduhs$demo_osduhs_mother_edu <- ifelse(grepl('attended', osduhs$demo_osduhs_mother_edu), 
                                        'Attended college or hs or uni',
                                        ifelse(grepl('graduated', osduhs$demo_osduhs_mother_edu),
                                               'graduated college or hs or uni',
                                               ifelse(grepl("don't", osduhs$demo_osduhs_mother_edu),
                                                      'Dont know',
                                                      ifelse(is.na(osduhs$demo_osduhs_mother_edu),
                                                             NA, 
                                                             ifelse(grepl('did not', osduhs$demo_osduhs_mother_edu),
                                                                          'No highschool', 'No mother')))))


# reocde demo_osduhs_grade
summary(as.factor(osduhs$demo_osduhs_grade))
osduhs$demo_osduhs_grade <- ifelse(grepl('6|11/12', osduhs$demo_osduhs_grade), 
                                    NA, 
                                   ifelse(grepl('7|8|9', osduhs$demo_osduhs_grade),
                                          'Grade 7-9',
                                          ifelse(grepl('10|grade 11|grade 12', osduhs$demo_osduhs_grade),
                                                 'Grade 10-12', osduhs$demo_osduhs_grade)))

# reocde ed_osduhs_avg_marks
summary(as.factor(osduhs$ed_osduhs_avg_marks))
osduhs$ed_osduhs_avg_marks <- ifelse(grepl('50%|60%', osduhs$ed_osduhs_avg_marks), 
                                    'below 70%', 
                                   ifelse(is.na(osduhs$ed_osduhs_avg_marks), 
                                          NA, as.character(osduhs$ed_osduhs_avg_marks)))
                                          

# recode ed_avg_marks 
summary(as.factor(osduhs$ed_osduhs_avg_marks))
# ed_osduhs_avg_marks
# ds_osduhs_close_with_people_at_school 
summary(as.factor(osduhs$ds_osduhs_close_with_people_at_school))
# cv_osduhs_social_media
summary(as.factor(osduhs$ce_osduhs_social_media))
# hw_osduhs_selfrate_mental_health
summary(as.factor(osduhs$hw_osduhs_mental_health))

# osduhs <- restructure_data_types(osduhs, convert_from  = 'character')


```


## Using prescrption pain medication with out a prescription at least once

# Mother and father status at home

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}
# relevel factors for the model
# 'father_type_at_home', 'mother_type_at_home', 'demo_osduhs_father_edu', 'demo_osduhs_mother_edu',  'demo_osduhs_grade', 'ed_osduhs_avg_marks', 'ds_osduhs_close_with_people_at_school' , 'cv_osduhs_social_media' , 'hw_osduhs_mental_health', 'demo_osduhs_pop_weight')
osduhs$demo_osduhs_father_type_at_home <- as.factor(osduhs$demo_osduhs_father_type_at_home)
summary(osduhs$demo_osduhs_father_type_at_home)
osduhs$demo_osduhs_father_type_at_home <- relevel(osduhs$demo_osduhs_father_type_at_home, ref = 'No father figure at home')

osduhs$demo_osduhs_mother_type_at_home <- as.factor(osduhs$demo_osduhs_mother_type_at_home)
summary(osduhs$demo_osduhs_mother_type_at_home)
osduhs$demo_osduhs_mother_type_at_home <- relevel(osduhs$demo_osduhs_mother_type_at_home, ref = 'No mother figure at home')

osduhs$demo_osduhs_father_edu <- as.factor(osduhs$demo_osduhs_father_edu)
summary(osduhs$demo_osduhs_father_edu)
osduhs$demo_osduhs_father_edu <- relevel(osduhs$demo_osduhs_father_edu, ref = 'No father')

osduhs$demo_osduhs_mother_edu <- as.factor(osduhs$demo_osduhs_mother_edu)
summary(osduhs$demo_osduhs_mother_edu)
osduhs$demo_osduhs_mother_edu <- relevel(osduhs$demo_osduhs_mother_edu, ref = 'No mother')

osduhs$demo_osduhs_grade <- as.factor(osduhs$demo_osduhs_grade)
summary(osduhs$demo_osduhs_grade)
osduhs$demo_osduhs_grade <- relevel(osduhs$demo_osduhs_grade, ref = 'Grade 7-9')

osduhs$ds_osduhs_close_with_people_at_school <- as.factor(osduhs$ds_osduhs_close_with_people_at_school)
summary(as.factor(osduhs$ds_osduhs_close_with_people_at_school))
osduhs$ds_osduhs_close_with_people_at_school <- relevel(osduhs$ds_osduhs_close_with_people_at_school, ref = 'strongly disagree')

osduhs$hw_osduhs_mental_health <- as.factor(osduhs$hw_osduhs_mental_health)
summary(as.factor(osduhs$hw_osduhs_mental_health))
osduhs$hw_osduhs_mental_health<- relevel(osduhs$hw_osduhs_mental_health, ref = 'poor')

osduhs$demo_osduhs_race <- as.factor(osduhs$demo_osduhs_race)
summary(as.factor(osduhs$demo_osduhs_race))
osduhs$demo_osduhs_race <- relevel(osduhs$demo_osduhs_race, ref = 'White')

osduhs$ed_osduhs_avg_marks <- as.factor(osduhs$ed_osduhs_avg_marks)
summary(as.factor(osduhs$ed_osduhs_avg_marks))
osduhs$ed_osduhs_avg_marks <- relevel(osduhs$ed_osduhs_avg_marks, ref = 'below 70%')



# run model
custom_logit_mod(osduhs, 
                 model_vars = c('demo_osduhs_race', 'demo_osduhs_pop_weight'),
                 outcome_var = 'pain_pill_no_pres', 
                 weights = FALSE, 
                 mod_type = 'binomial')

# run model
custom_logit_mod(osduhs, 
                 model_vars = c('demo_osduhs_race','ed_osduhs_avg_marks' ,'demo_osduhs_pop_weight'),
                 outcome_var = 'pain_pill_no_pres', 
                 weights = FALSE, 
                 mod_type = 'binomial')

```


# education of mother and father

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}


custom_logit_mod(osduhs, 
                 model_vars = c('father_type_home', 'mother_type_home', 'demo_osduhs_father_edu', 'demo_osduhs_mother_edu', 
                                'demo_osduhs_pop_weight'),
                 outcome_var = 'pain_pill_no_pres', 
                 weights = FALSE, 
                 mod_type = 'binomial')

```

## Grade of student and average marks

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}


custom_logit_mod(osduhs, 
                 model_vars = c('father_type_home', 'mother_type_home', 'demo_osduhs_father_edu', 'demo_osduhs_mother_edu',  'demo_osduhs_grade', 'ed_osduhs_avg_marks', 'demo_osduhs_pop_weight'),
                 outcome_var = 'pain_pill_no_pres', 
                 weights = FALSE, 
                 mod_type = 'binomial')

```

## Closeness with other kids at school, social media time, mental health

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}


custom_logit_mod(osduhs, 
                 model_vars = c('father_type_home', 'mother_type_home', 'demo_osduhs_father_edu', 'demo_osduhs_mother_edu',  'demo_osduhs_grade', 'ed_osduhs_avg_marks', 'ds_osduhs_close_with_people_at_school' , 'cv_osduhs_social_media' , 'hw_osduhs_mental_health', 'demo_osduhs_pop_weight'),
                 outcome_var = 'pain_pill_no_pres', 
                 weights = FALSE, 
                 mod_type = 'binomial')

```
