---
title: "Youthrex raw data"
author: "www.databrew.cc"
output:
    html_document:
      toc: true
      theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA, error=FALSE}
library(knitr)
library(htmltools)
# no scientific notation
options(scipen=999)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

# Libraries
library(feather)
library(tidyverse)
library(googleVis)
library(RColorBrewer)
library(databrew)
op <- options(gvis.plot.tag='chart')


# Helper functions
source('functions.R')
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA, error=FALSE}
# read in census data 
census_all <- read_feather('data/census_all.feather')
```



# Tables

## Ontario

```{r}
geo_codes <- sort(unique(census_all$geo_code))
sis <- sort(unique(census_all$si))
# years <- sort(unique(census_all$year))
# ages <- sort(unique(census_all$age))
# sexes <- sort(unique(census_all$sex))
# pobs <- sort(unique(census_all$pob))
# vms <- sort(unique(census_all$vm))
counter <- 0
chunks <- c()
tables <- list()

for(si in sis){
  counter <- counter + 1
  # cat(paste0('### ', si, '\n\n'))
  this_si <- si
  x <- census_all
  x <-
    x %>%
    filter(geo_code == '3500',
           si == this_si) %>%
    group_by(year, si) %>%
    summarise(value = sum(value)) %>%
    ungroup
  header <- x$si[1]
  x <- x %>% dplyr::select(-si)
  tables[[counter]] <- x

  chunks[counter] <- paste0('\n\n### ', header, '\n\n```{r}\nprettify(tables[[', counter, ']])\n```\n')
}

chunks <- paste0(chunks, collapse = '')
```

```{r}
# Write our order / child-calls to a doc
file_connection <- file('children.Rmd')
writeLines(paste0('---\noutput: html_document\n---\n\n', 
                  chunks), 
           file_connection)
close(file_connection)
```

```{r child='children.Rmd', echo = FALSE}
# Now, we simply include "children.Rmd" to construct our doc
# (ie, children is the child doc, and each section is a grandchild)
```

```{r, results='hide'}
# Having already called the auto-generated children.Rmd, we can delete it
file.remove('children.Rmd')
```


## Census areas

```{r}
counter <- 0
chunks <- c()
tables <- list()

for(si in sis){
  for(geo_code in geo_codes){
  counter <- counter + 1
  this_si <- si
  this_geo_code <- geo_code
  x <- census_all
  x <-
    x %>%
    filter(geo_code == this_geo_code,
           si == this_si) %>%
    group_by(year, si) %>%
    summarise(value = sum(value)) %>%
    ungroup
  header <- x$si[1]
  geo <- census_all$geo[census_all$geo_code == this_geo_code][1]
  header <- paste0(geo, ': ', header)
  x <- x %>% dplyr::select(-si)
  tables[[counter]] <- x

  chunks[counter] <- paste0('\n\n### ', header, '\n\n```{r}\nprettify(tables[[', counter, ']])\n```\n')
  }
}

chunks <- paste0(chunks, collapse = '')
```

```{r}
# Write our order / child-calls to a doc
file_connection <- file('children.Rmd')
writeLines(paste0('---\noutput: html_document\n---\n\n', 
                  chunks), 
           file_connection)
close(file_connection)
```

```{r child='children.Rmd', echo = FALSE}
# Now, we simply include "children.Rmd" to construct our doc
# (ie, children is the child doc, and each section is a grandchild)
```

```{r, results='hide'}
# Having already called the auto-generated children.Rmd, we can delete it
file.remove('children.Rmd')
```

