---
title: "Youthrex data table script"
author: "Ben Brew"
output:
    html_document:
      toc: true
      theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA, error=FALSE}
# no scientific notation
options(scipen=999)
library(tidyverse)
library(dplyr)
library(knitr)


```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA, error=FALSE}
##########
# read in and finish cleaning census data 
##########
# dat <- read_feather('../data/census_all.feather')



```

```{r, results='asis'}

#########
# function that takes a data frame, geography and year argument for subset argument to subset, 
# and summarzies special indicators for each visibe minority
#########
data_frame <- dat
geography = 'Ontario'
year = '2001'
pob = "Born in Canada" 
by_vis_min <- function(data_frame, geography, year) {

    # subset by year 
    dat_sub <- data_frame[data_frame$year == year,]
    dat_sub$year <- NULL
    
    # subset by geography
    dat_sub <- dat_sub[dat_sub$geo == geography,]
    dat_sub$geo <- 
       dat_sub$geo_code <- NULL
    
    
    # subset by inside or outside canada 
    dat_sub <- dat_sub[dat_sub$pob == pob,]
    dat_sub$pob <- NULL
    
    # get visibe minority
    vis_min <- as.character(unique(dat_sub$vm))

    # loop through each visible minority group and get special_indicators by age and sex
    for(vm in vis_min){
      temp_vm <- dat_sub[dat_sub$vm == vm,]
    }

}


# remove geography if ontario. remove non_response_rate for now
dat_ontario$geography <- NULL
dat_ontario$non_response_rate <- NULL

# group by get an indicator for column name 
variable_names <- as.character(colnames(dat_ontario))

# # remove any row that has total by looping through columns 
remove_total <- function(data_frame, vars) {
  for(v in 1:length(vars)) {
    data_frame <- data_frame[!grepl('total', data_frame[, v]),]
    print(v)
  }
  return(data_frame)
}

dat_ontario <- remove_total(dat_ontario, variable_names)
# temp_11 <- temp_no_total[!duplicated(c(temp_no_total$age_group,
#                  temp_no_total$sex,
#                  temp_no_total$pob,
#                  temp_no_total$vis_min,
#                  temp_no_total$special_ind, 
#                  temp_no_total$year)),]
# 
# temp <- remove_total(data_frame = dat_ontario, vars =  variable_names)
# 
# temp <- apply(dat_ontario, 2, function(x) x[!grepl('total', x)])
# temp <- do.call()
# temp <- dat_ontario[!grepl('total', dat_ontario), ]

# takes a vis_min level and subsets on that
# then groups by age and summarises each one 
# visible_min = 'chinese'

vis_min_summarise <- function(visible_min){
  
  # get visible minority category
  vis_min_sub <- dat_ontario[dat_ontario$vis_min == visible_min,]
  
  ##########
  # group by year and age_group and summarise sex
  ##########
  vis_min_sex <- vis_min_sub %>%
    group_by(year, age_group) %>%
    summarise(sum_male = sum(value[sex == 'male']))
  ##########
  # group by year and age_group and summarise pob
  ##########
  
  ##########
  # group by year and age_group and summarise special_ind
  ##########
  
  
}








##########
# function that takes a variable and groups by that variable with year and age, summrises
# pob and special ind
##########
data_frame <- dat_ontario
var <- 'vis_min'

get_stats <- function(data_frame, var) {
  
  # get other varibles
  other_variables <- colnames(data_frame)[!grepl(var, colnames(data_frame))]
  for(y_variable in other_variables) {
    # get data with x,y variables as well as year and value
    var_data <- data_frame[, c(var, other_variables)]
    
    # group by year, age, and y variable to get sum of year, age group, and y totals
    year_x_y <- x_y_data %>%
      group_by_('year', 'vis_min', x_variable, y_variable) %>%
      summarise(total_x_y = sum(value, na.rm = T)) %>% spread(key = x_variable, value = total_x_y) 
    
    # change colnames 
    colnames(year_x_y) <- make.names(gsub(" ", "_", colnames(year_x_y)))
    
    # make total comlumn
    year_x_y$tot <- sum(year_x_y$X15_to_19_years, year_x_y$X15_to_24_years, 
                        year_x_y$X20_to_24_years, year_x_y$X25_to_29_years)
    
    # total_x_y/total_y - ex 15_19 make 40% percent of youth born in canadacanada
    year_x_y$percent_ages_15_to_19 <- round((year_x_y$X15_to_19_years/year_x_y$tot)*100, 2)
    year_x_y$percent_ages_15_to_24 <- round((year_x_y$X15_to_24_years/year_x_y$tot)*100, 2)
    year_x_y$percent_ages_20_to_24 <- round((year_x_y$X20_to_24_years/year_x_y$tot)*100, 2)
    year_x_y$percent_ages_25_to_29 <- round((year_x_y$X25_to_29_years/year_x_y$tot)*100, 2)
    
    # remove unneeded oclumns
    year_x_y$X15_to_19_years <- year_x_y$X15_to_24_years <-
      year_x_y$X20_to_24_years <- year_x_y$X25_to_29_years <-
      year_x_y$tot <- NULL
    
    # break up by year 
    x_y_2001 <- subset(year_x_y, year == '2001')
    x_y_2006 <- subset(year_x_y, year == '2006')
    x_y_2011 <- subset(year_x_y, year == '2011')
    
    # remove year
    x_y_2001$year <-
      x_y_2006$year <-     
      x_y_2011$year <- NULL
    
    
    #     table_title <- paste0(x_variable, ' by ', y_variable, ' for ', '2011')
    #     kable(x_y_2011, caption =table_title)
    
  }
  
}

get_stats(dat_ontario, x_variable = 'age_group')

```


```{r, results='asis'}

# remove geography if ontario. remove non_response_rate for now
dat_ontario$geography <- NULL
dat_ontario$non_response_rate <- NULL

# group by get an indicator for column name 
variable_names <- as.character(colnames(dat_ontario))

# # remove any row that has total by looping through columns 
remove_total <- function(data_frame, vars) {
  for(v in 1:length(vars)) {
    data_frame <- data_frame[!grepl('total', data_frame[, v]),]
    print(v)
  }
  return(data_frame)
}

dat_ontario <- remove_total(dat_ontario, variable_names)


##########
# function that tak
##########
data_frame <- dat_ontario
x_variable <- 'age_group'
y_variable <- 'pob'

get_vis_min_stats <- function(data_frame, x_variable) {
  
  for (x_variable in variable_names) {
    # define other variable 
    other_variables <- variable_names[variable_names != x_variable]
    
    # loop through other variables and group by variable to summarise the other variable
    for(y_variable in other_variables) {
      # get data with x,y variables as well as year and value
      x_y_data <- data_frame[, c('year', x_variable, y_variable, 'value')]
      
      # group by year, age, and y variable to get sum of year, age group, and y totals
      year_x_y <- x_y_data %>%
        group_by_('year', 'vis_min', x_variable, y_variable) %>%
        summarise(total_x_y = sum(value, na.rm = T)) %>% spread(key = x_variable, value = total_x_y) 
      
      # change colnames 
      colnames(year_x_y) <- make.names(gsub(" ", "_", colnames(year_x_y)))
      
      # make total comlumn
      year_x_y$tot <- sum(year_x_y$X15_to_19_years, year_x_y$X15_to_24_years, 
                          year_x_y$X20_to_24_years, year_x_y$X25_to_29_years)
      
      # total_x_y/total_y - ex 15_19 make 40% percent of youth born in canadacanada
      year_x_y$percent_ages_15_to_19 <- round((year_x_y$X15_to_19_years/year_x_y$tot)*100, 2)
      year_x_y$percent_ages_15_to_24 <- round((year_x_y$X15_to_24_years/year_x_y$tot)*100, 2)
      year_x_y$percent_ages_20_to_24 <- round((year_x_y$X20_to_24_years/year_x_y$tot)*100, 2)
      year_x_y$percent_ages_25_to_29 <- round((year_x_y$X25_to_29_years/year_x_y$tot)*100, 2)
      
      # remove unneeded oclumns
      year_x_y$X15_to_19_years <- year_x_y$X15_to_24_years <-
        year_x_y$X20_to_24_years <- year_x_y$X25_to_29_years <-
        year_x_y$tot <- NULL
      
      # break up by year 
      x_y_2001 <- subset(year_x_y, year == '2001')
      x_y_2006 <- subset(year_x_y, year == '2006')
      x_y_2011 <- subset(year_x_y, year == '2011')
      
      # remove year
      x_y_2001$year <-
        x_y_2006$year <-     
        x_y_2011$year <- NULL
      
      # 
      #     # make table for each one 
      #     table_title <- paste0(x_variable, ' by ', y_variable, ' for ', '2001')
      #     kable(x_y_2001, caption =table_title)
      #     
      #     table_title <- paste0(x_variable, ' by ', y_variable, ' for ', '2006')
      #     kable(x_y_2006, caption =table_title)
      #     
      #     table_title <- paste0(x_variable, ' by ', y_variable, ' for ', '2011')
      #     kable(x_y_2011, caption =table_title)
      
    }
    
  }
  
}

get_stats(dat_ontario, x_variable = 'age_group')

```



```{r}

##########
# function that takes one of the 6 variables and creates a data table with summary statistics in
# both raw and percent form. And possible a button to download that data
##########

make_table <-function(x) {
  # # get total string 
  # unique_string_x <- unique(dat_ontario[,x_variable])
  # unique_string_y <- unique(dat_ontario[,y_variable])
  # #get total string
  # total_string_x <- as.character(unique_string_x[grepl('total', unique_string_x)])
  # total_string_y <- as.character(unique_string_y[grepl('total', unique_string_y)])
  # # remove total from the two variables
  # remove_totals <- paste(total_string_x, total_string_y, sep = '|')
  # dat_sub <- dat_ontario[grepl(remove_totals, dat_ontario[, x_variable]),]
  # dat_sub <- dat_ontario[grepl(remove_totals, dat_ontario[, y_variable]),]
}

```




