---
title: "Survey stats for Gss10"
author: "Ben Brew"
date: "January 6, 2018"
output: html_document
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE}

# Libraries
library(tidyverse)
library(glmnet)
library(knitr)
library(Hmisc)
library(RColorBrewer)
library(plotly)
library(databrew)
library(ggmap)
library(reshape2)
library(memisc)
library(texreg)


# Turn off scientific notation
options(scipen = '999')

# Basic knitr options
knitr::opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, # Render report, even with errors
               cache = F)
# source functions
source('../functions.R')

# Get all locations
if('processed_survey_data.RData' %in% dir('data')){
  load('../data/processed_survey_data.RData')
} else { 
  source('../global.R')
}
```

# General Social Survey 2010


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, results = 'asis',error= FALSE}

# get lfs data from survey list 
gss <- survey[[2]]

# make all characters
gss <- restructure_data_types(gss, convert_from  = 'character')

str(gss)

```

